CREATE TABLE EMPLOYEES
(
    Emp_ID NUMERIC(6) PRIMARY KEY,
    Emp_NAME VARCHAR(255),
    Gender CHAR(1),
    Date_Of_Birth DATE,
    Department NUMERIC(6),
    Salary NUMERIC(6),
    FOREIGN KEY (DEPARTMENT) REFERENCES DEPARTMENTS(DEPT_ID)
);