CREATE TABLE FACULTIES
(
 Emp_ID NUMERIC(6),
 Experience NUMERIC(2),
 Course_ID NUMERIC(6),
 FOREIGN KEY (Emp_ID) REFERENCES EMPLOYEES(Emp_ID),
 FOREIGN KEY (Course_ID) REFERENCES COURSES(Course_ID)
);