CREATE TABLE STUDENTS
(
    Student_ID NUMERIC(8) PRIMARY KEY,
    F_NAME VARCHAR(255),
    L_NAME VARCHAR(255),
    Date_Of_Birth DATE,
    GENDER CHAR(1)),
    PHONE NUMERIC(10) UNIQUE ,
    EMAIL VARCHAR(255) UNIQUE,
    House_Number VARCHAR(255),
    CITY VARCHAR(255),
    STREET VARCHAR(255),
    TOWN VARCHAR(255),
    SEMESTER NUMERIC,
    CPI DECIMAL(3, 2)
);