CREATE TABLE JOINED
(
    Student_ID NUMERIC(8),
    Club_ID NUMERIC(6),
    FOREIGN KEY (Student_ID) REFERENCES STUDENTS(STUDENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (Club_ID) REFERENCES CLUBS(Club_ID) ON DELETE CASCADE
);